# theme.toml template for a Hugo theme
name = "portfolique-hugo-theme"
license = "MIT"
licenselink = ""
description = "Portfolio theme for Hugo"
homepage = ""
tags = ["Hugo", "Theme", "Portfolio", "Tailwind"]
features = []
min_version = "0.69"

[author]
  name = "Varun A P"
  homepage = "https://github.com/apvarun"
